auth.method: noAuth
collector.dmaap.streamid: fault=ves-fault|syslog=ves-syslog|heartbeat=ves-heartbeat|measurement=ves-measurement|measurementsForVfScaling=ves-measurement|mobileFlow=ves-mobileflow|other=ves-other|stateChange=ves-statechange|thresholdCrossingAlert=ves-thresholdCrossingAlert|voiceQuality=ves-voicequality|sipSignaling=ves-sipsignaling|notification=ves-notification|pnfRegistration=ves-pnfRegistration|3GPP-FaultSupervision=ves-3gpp-fault-supervision|3GPP-Heartbeat=ves-3gpp-heartbeat|3GPP-Provisioning=ves-3gpp-provisioning|3GPP-PerformanceAssurance=ves-3gpp-performance-assurance
collector.dynamic.config.update.frequency: "5"
collector.externalSchema.checkflag: 1
collector.externalSchema.mappingFileLocation: ./etc/externalRepo/schema-map.json
collector.externalSchema.schemasLocation: ./etc/externalRepo/
collector.inputQueue.maxPending: "8096"
collector.keystore.file.location: ./etc/keystore
collector.keystore.passwordfile: ./etc/passwordfile
collector.schema.checkflag: "1"
collector.schema.file: '{"v1":"./etc/CommonEventFormat_27.2.json","v2":"./etc/CommonEventFormat_27.2.json","v3":"./etc/CommonEventFormat_27.2.json","v4":"./etc/CommonEventFormat_27.2.json","v5":"./etc/CommonEventFormat_28.4.1.json","v7":"./etc/CommonEventFormat_30.2.1_ONAP.json"}'
collector.service.port: "8080"
collector.service.secure.port: "8443"
collector.truststore.file.location: ./etc/truststore
collector.truststore.passwordfile: ./etc/trustpasswordfile
event.externalSchema.schemaRefPath: $.event.stndDefinedFields.schemaReference
event.externalSchema.stndDefinedDataPath: $.event.stndDefinedFields.data
event.transform.flag: "0"
header.authlist: sample1,$2a$10$0buh.2WeYwN868YMwnNNEuNEAMNYVU9.FSMJGyIKV3dGET/7oGOi6|demouser,$2a$10$1cc.COcqV/d3iT2N7BjPG.S6ZKv2jpb9a5MV.o7lMih/GpjJRX.Ce
services_calls: []
streams_publishes:
  ves-3gpp-fault-supervision:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.SEC_3GPP_FAULTSUPERVISION_OUTPUT
    type: message_router
  ves-3gpp-heartbeat:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.SEC_3GPP_HEARTBEAT_OUTPUT
    type: message_router
  ves-3gpp-performance-assurance:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.SEC_3GPP_PERFORMANCEASSURANCE_OUTPUT
    type: message_router
  ves-3gpp-provisioning:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.SEC_3GPP_PROVISIONING_OUTPUT
    type: message_router
  ves-fault:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.SEC_FAULT_OUTPUT
    type: message_router
  ves-heartbeat:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.SEC_HEARTBEAT_OUTPUT
    type: message_router
  ves-measurement:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.VES_MEASUREMENT_OUTPUT
    type: message_router
  ves-notification:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.VES_NOTIFICATION_OUTPUT
    type: message_router
  ves-other:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.SEC_OTHER_OUTPUT
    type: message_router
  ves-pnfRegistration:
    dmaap_info:
      topic_url: http://message-router:3904/events/unauthenticated.VES_PNFREG_OUTPUT
    type: message_router

