include environment.config

#targets
generate:
	./generate.sh $(REPOSITORY_URL) $(REPOSITORY_BRANCH) $(SCHEMAS_LOCATION) $(VENDOR_NAME) $(SPEC_CONFIGMAP_FILENAME) $(K8S_CONFIGMAP_NAME) $(MAPPING_FILE_NAME)

install:
	./install.sh